# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/top.xdc

# Block Designs: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/base.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_axi_dma_0_0/base_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_dma_0_0 || ORIG_REF_NAME==base_axi_dma_0_0} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_axi_dma_1_0/base_axi_dma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_dma_1_0 || ORIG_REF_NAME==base_axi_dma_1_0} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_axi_mem_intercon_0/base_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_mem_intercon_0 || ORIG_REF_NAME==base_axi_mem_intercon_0} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_axis_switch_0_0/base_axis_switch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axis_switch_0_0 || ORIG_REF_NAME==base_axis_switch_0_0} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_ps7_0/base_ps7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ps7_0 || ORIG_REF_NAME==base_ps7_0} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_ps7_axi_periph_0/base_ps7_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ps7_axi_periph_0 || ORIG_REF_NAME==base_ps7_axi_periph_0} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_rst_ps7_100M_0/base_rst_ps7_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rst_ps7_100M_0 || ORIG_REF_NAME==base_rst_ps7_100M_0} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_simple_sum_0_0/base_simple_sum_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_simple_sum_0_0 || ORIG_REF_NAME==base_simple_sum_0_0} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_stream_mult_0_0/base_stream_mult_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_stream_mult_0_0 || ORIG_REF_NAME==base_stream_mult_0_0} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_mult_constant_0_0/base_mult_constant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mult_constant_0_0 || ORIG_REF_NAME==base_mult_constant_0_0} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_cifar_10_0_0/base_cifar_10_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_cifar_10_0_0 || ORIG_REF_NAME==base_cifar_10_0_0} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_xbar_0/base_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_0 || ORIG_REF_NAME==base_xbar_0} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_xbar_1/base_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_1 || ORIG_REF_NAME==base_xbar_1} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_us_0/base_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_us_0 || ORIG_REF_NAME==base_auto_us_0} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_us_1/base_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_us_1 || ORIG_REF_NAME==base_auto_us_1} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_us_2/base_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_us_2 || ORIG_REF_NAME==base_auto_us_2} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_us_3/base_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_us_3 || ORIG_REF_NAME==base_auto_us_3} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_pc_0/base_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_0 || ORIG_REF_NAME==base_auto_pc_0} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_pc_1/base_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_1 || ORIG_REF_NAME==base_auto_pc_1} -quiet] -quiet

# IP: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_s00_mmu_0/base_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_s00_mmu_0 || ORIG_REF_NAME==base_s00_mmu_0} -quiet] -quiet

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_axi_dma_0_0/base_axi_dma_0_0_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_axi_dma_0_0/base_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_dma_0_0 || ORIG_REF_NAME==base_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_axi_dma_0_0/base_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_dma_0_0 || ORIG_REF_NAME==base_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_axi_dma_1_0/base_axi_dma_1_0_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_axi_dma_1_0/base_axi_dma_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_dma_1_0 || ORIG_REF_NAME==base_axi_dma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_axi_dma_1_0/base_axi_dma_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_dma_1_0 || ORIG_REF_NAME==base_axi_dma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_axis_switch_0_0/base_axis_switch_0_0_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_ps7_0/base_ps7_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_ps7_0 || ORIG_REF_NAME==base_ps7_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_rst_ps7_100M_0/base_rst_ps7_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_rst_ps7_100M_0 || ORIG_REF_NAME==base_rst_ps7_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_rst_ps7_100M_0/base_rst_ps7_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_rst_ps7_100M_0 || ORIG_REF_NAME==base_rst_ps7_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_rst_ps7_100M_0/base_rst_ps7_100M_0_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_simple_sum_0_0/constraints/simple_sum_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_stream_mult_0_0/constraints/stream_mult_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_mult_constant_0_0/constraints/mult_constant_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_cifar_10_0_0/constraints/cifar_10_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_xbar_0/base_xbar_0_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_xbar_1/base_xbar_1_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_us_0/base_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_auto_us_0 || ORIG_REF_NAME==base_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_us_0/base_auto_us_0_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_us_1/base_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_auto_us_1 || ORIG_REF_NAME==base_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_us_1/base_auto_us_1_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_us_2/base_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_auto_us_2 || ORIG_REF_NAME==base_auto_us_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_us_2/base_auto_us_2_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_us_3/base_auto_us_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_auto_us_3 || ORIG_REF_NAME==base_auto_us_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_us_3/base_auto_us_3_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_pc_0/base_auto_pc_0_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_auto_pc_1/base_auto_pc_1_ooc.xdc

# XDC: d:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/ip/base_s00_mmu_0/base_s00_mmu_0_ooc.xdc

# XDC: D:/08_Verilog/pro/PYNQ-Classification-master/hw/base_project/base/base_ooc.xdc
