// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _AXI_DMA_SLAVE_HH_
#define _AXI_DMA_SLAVE_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "cifar_10_mul_32s_bkb.h"

namespace ap_rtl {

struct AXI_DMA_SLAVE : public sc_module {
    // Port declarations 17
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_in< sc_lv<32> > in_stream_TDATA;
    sc_in< sc_logic > in_stream_TVALID;
    sc_out< sc_logic > in_stream_TREADY;
    sc_in< sc_logic > in_stream_TLAST;
    sc_out< sc_lv<32> > out_stream_V_V_din;
    sc_in< sc_logic > out_stream_V_V_full_n;
    sc_out< sc_logic > out_stream_V_V_write;


    // Module declarations
    AXI_DMA_SLAVE(sc_module_name name);
    SC_HAS_PROCESS(AXI_DMA_SLAVE);

    ~AXI_DMA_SLAVE();

    sc_trace_file* mVcdFile;

    cifar_10_mul_32s_bkb<1,1,32,32,32>* cifar_10_mul_32s_bkb_U1;
    cifar_10_mul_32s_bkb<1,1,32,32,32>* cifar_10_mul_32s_bkb_U2;
    cifar_10_mul_32s_bkb<1,1,32,32,32>* cifar_10_mul_32s_bkb_U3;
    cifar_10_mul_32s_bkb<1,1,32,32,32>* cifar_10_mul_32s_bkb_U4;
    cifar_10_mul_32s_bkb<1,1,32,32,32>* cifar_10_mul_32s_bkb_U5;
    cifar_10_mul_32s_bkb<1,1,32,32,32>* cifar_10_mul_32s_bkb_U6;
    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<15> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_lv<32> > in_stream_V_data_V_0_data_out;
    sc_signal< sc_logic > in_stream_V_data_V_0_vld_in;
    sc_signal< sc_logic > in_stream_V_data_V_0_vld_out;
    sc_signal< sc_logic > in_stream_V_data_V_0_ack_in;
    sc_signal< sc_logic > in_stream_V_data_V_0_ack_out;
    sc_signal< sc_lv<32> > in_stream_V_data_V_0_payload_A;
    sc_signal< sc_lv<32> > in_stream_V_data_V_0_payload_B;
    sc_signal< sc_logic > in_stream_V_data_V_0_sel_rd;
    sc_signal< sc_logic > in_stream_V_data_V_0_sel_wr;
    sc_signal< sc_logic > in_stream_V_data_V_0_sel;
    sc_signal< sc_logic > in_stream_V_data_V_0_load_A;
    sc_signal< sc_logic > in_stream_V_data_V_0_load_B;
    sc_signal< sc_lv<2> > in_stream_V_data_V_0_state;
    sc_signal< sc_logic > in_stream_V_data_V_0_state_cmp_full;
    sc_signal< sc_logic > in_stream_V_last_0_vld_in;
    sc_signal< sc_logic > in_stream_V_last_0_ack_out;
    sc_signal< sc_lv<2> > in_stream_V_last_0_state;
    sc_signal< sc_logic > in_stream_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_logic > ap_CS_fsm_pp1_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp1_iter0;
    sc_signal< bool > ap_block_pp1_stage0;
    sc_signal< sc_lv<1> > exitcond1_fu_149_p2;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > exitcond_fu_129_p2;
    sc_signal< sc_logic > out_stream_V_V_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp1_iter1;
    sc_signal< sc_lv<1> > exitcond1_reg_226;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<1> > exitcond_reg_207;
    sc_signal< sc_lv<32> > i1_reg_75;
    sc_signal< sc_lv<32> > i_reg_86;
    sc_signal< sc_lv<32> > reg_102;
    sc_signal< bool > ap_block_state2;
    sc_signal< bool > ap_block_state11_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state12_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< bool > ap_block_state16_pp1_stage0_iter0;
    sc_signal< bool > ap_block_state17_pp1_stage0_iter1;
    sc_signal< bool > ap_block_pp1_stage0_11001;
    sc_signal< sc_lv<1> > tmp_s_fu_107_p2;
    sc_signal< sc_lv<1> > tmp_s_reg_160;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<32> > tmp_data_V_2_reg_164;
    sc_signal< bool > ap_block_state3;
    sc_signal< sc_lv<32> > tmp_data_V_3_reg_170;
    sc_signal< bool > ap_block_state4;
    sc_signal< sc_lv<32> > tmp_data_V_4_reg_176;
    sc_signal< bool > ap_block_state5;
    sc_signal< sc_lv<32> > tmp_data_V_5_reg_182;
    sc_signal< bool > ap_block_state6;
    sc_signal< sc_lv<32> > KER_size_0_fu_113_p2;
    sc_signal< sc_lv<32> > KER_size_0_reg_187;
    sc_signal< bool > ap_block_state8;
    sc_signal< sc_lv<32> > IFM_size_0_fu_117_p2;
    sc_signal< sc_lv<32> > IFM_size_0_reg_192;
    sc_signal< sc_lv<32> > KER_size_1_fu_121_p2;
    sc_signal< sc_lv<32> > KER_size_1_reg_197;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<32> > KER_bound_fu_125_p2;
    sc_signal< sc_lv<32> > KER_bound_reg_202;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<32> > i_1_fu_134_p2;
    sc_signal< sc_lv<32> > IFM_size_1_fu_140_p2;
    sc_signal< sc_lv<32> > IFM_size_1_reg_216;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_lv<32> > IFM_bound_fu_144_p2;
    sc_signal< sc_lv<32> > IFM_bound_reg_221;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<32> > i_17_fu_154_p2;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state11;
    sc_signal< bool > ap_block_pp1_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp1_exit_iter0_state16;
    sc_signal< bool > ap_block_state7;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< bool > ap_block_pp1_stage0_01001;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<15> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    sc_signal< sc_logic > ap_idle_pp1;
    sc_signal< sc_logic > ap_enable_pp1;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<15> ap_ST_fsm_state1;
    static const sc_lv<15> ap_ST_fsm_state2;
    static const sc_lv<15> ap_ST_fsm_state3;
    static const sc_lv<15> ap_ST_fsm_state4;
    static const sc_lv<15> ap_ST_fsm_state5;
    static const sc_lv<15> ap_ST_fsm_state6;
    static const sc_lv<15> ap_ST_fsm_state7;
    static const sc_lv<15> ap_ST_fsm_state8;
    static const sc_lv<15> ap_ST_fsm_state9;
    static const sc_lv<15> ap_ST_fsm_state10;
    static const sc_lv<15> ap_ST_fsm_pp0_stage0;
    static const sc_lv<15> ap_ST_fsm_state13;
    static const sc_lv<15> ap_ST_fsm_state14;
    static const sc_lv<15> ap_ST_fsm_state15;
    static const sc_lv<15> ap_ST_fsm_pp1_stage0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_E;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_B;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_pp1_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_pp1_stage0();
    void thread_ap_block_pp1_stage0_01001();
    void thread_ap_block_pp1_stage0_11001();
    void thread_ap_block_pp1_stage0_subdone();
    void thread_ap_block_state1();
    void thread_ap_block_state11_pp0_stage0_iter0();
    void thread_ap_block_state12_pp0_stage0_iter1();
    void thread_ap_block_state16_pp1_stage0_iter0();
    void thread_ap_block_state17_pp1_stage0_iter1();
    void thread_ap_block_state2();
    void thread_ap_block_state3();
    void thread_ap_block_state4();
    void thread_ap_block_state5();
    void thread_ap_block_state6();
    void thread_ap_block_state7();
    void thread_ap_block_state8();
    void thread_ap_condition_pp0_exit_iter0_state11();
    void thread_ap_condition_pp1_exit_iter0_state16();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_enable_pp1();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_idle_pp1();
    void thread_ap_ready();
    void thread_exitcond1_fu_149_p2();
    void thread_exitcond_fu_129_p2();
    void thread_i_17_fu_154_p2();
    void thread_i_1_fu_134_p2();
    void thread_in_stream_TDATA_blk_n();
    void thread_in_stream_TREADY();
    void thread_in_stream_V_data_V_0_ack_in();
    void thread_in_stream_V_data_V_0_ack_out();
    void thread_in_stream_V_data_V_0_data_out();
    void thread_in_stream_V_data_V_0_load_A();
    void thread_in_stream_V_data_V_0_load_B();
    void thread_in_stream_V_data_V_0_sel();
    void thread_in_stream_V_data_V_0_state_cmp_full();
    void thread_in_stream_V_data_V_0_vld_in();
    void thread_in_stream_V_data_V_0_vld_out();
    void thread_in_stream_V_last_0_ack_out();
    void thread_in_stream_V_last_0_vld_in();
    void thread_internal_ap_ready();
    void thread_out_stream_V_V_blk_n();
    void thread_out_stream_V_V_din();
    void thread_out_stream_V_V_write();
    void thread_real_start();
    void thread_start_out();
    void thread_start_write();
    void thread_tmp_s_fu_107_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
